version: "3.9"
services:
  auth:
    image: weberc2/auth:30c8cd75
    command: [ "/bin/auth" ]
    ports: [ 8081:8081 ]
    environment:
      AUTH_ADDR: :8081
      AUTH_HOST_NAME: http://localhost:8081
      AUTH_ISSUER: localhost
      AUTH_AUDIENCE: "*.weberc2.com"
      AUTH_NOTIFICATION_SENDER: auth@weberc2.com
      AUTH_DEFAULT_REDIRECT_LOCATION: http://localhost:8080/posts/foo/comments/__toplevel__/replies
      AUTH_REDIRECT_DOMAIN: "localhost:8080"
      AUTH_BASE_URL: http://localhost:8081
      AWS_REGION: us-east-2

      # Secrets
      AUTH_ACCESS_SIGNING_KEY: "${AUTH_ACCESS_SIGNING_KEY}"
      AUTH_REFRESH_SIGNING_KEY: "${AUTH_REFRESH_SIGNING_KEY}"
      AUTH_RESET_SIGNING_KEY: "${AUTH_RESET_SIGNING_KEY}"
      AWS_ACCESS_KEY_ID: "${AUTH_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AUTH_AWS_SECRET_ACCESS_KEY}"

  comments:
    build: "."
    ports: [ 8080:8080 ]
    environment:
      ADDR: ":8080"
      LOGIN_URL: http://localhost:8081/login
      LOGOUT_URL: http://localhost:8081/logout
      BASE_URL: http://localhost:8080
      AUTH_BASE_URL: http://localhost:8081
      BUCKET: weberc2-comments
      ACCESS_KEY: "${COMMENTS_ACCESS_PUBLIC_KEY}"
      AWS_REGION: us-east-2
      AUTH_DISABLED_USER: "${AUTH_DISABLED_USER}"

      # Secrets
      AWS_ACCESS_KEY_ID: "${COMMENTS_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${COMMENTS_AWS_SECRET_ACCESS_KEY}"
